api/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view

app_name = "api"

urlpatterns = [
    path("courses/", views.GetCourses.as_view()),
    path(
        "courses/<int:courseid>/",
        views.CourseDetail.as_view(
            {
                "get": "retrieve",
            }
        ),
        name="coursedetail",
    ),
    path(
        "openapi",
        get_schema_view(
            title="Your Project",
            description="API for all things …",
            version="1.0.0",
        ),
        name="openapi-schema",
    ),
    path(
        "redoc/",
        TemplateView.as_view(
            template_name="redoc.html",
            extra_context={"schema_url": "openapi-schema"},
        ),
        name="redoc",
    ),
    path(
        "updatedb/",
        views.storecoursesindb,
        name="updatebd",
    ),
]

courses/urls.py
from django.urls import path
from . import views


app_name = "courses"
urlpatterns = [
    path(
        "get_courses/",
        views.getcoursesinfo,
        name="getcourses",
    ),
    path(
        "course_detail/<int:id>",
        views.coursedetail,
        name="coursedetail",
    ),
    path(
        "course_detail/<int:courseid>/sessionregister/<int:sessionid>",
        views.sessionregister,
        name="sessionregister",
    ),
]

drf_test_task/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path(
        "auth/", include(("django.contrib.auth.urls", "authorisation"), namespace="auth")
    ),
    path("courses/", include("courses.urls", namespace="courses")),
    path("api/", include("api.urls", namespace="api")),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordChangeView,
    PasswordResetView,
)
from . import views
from django.urls import reverse_lazy


app_name = "users"
urlpatterns = [
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "signup/",
        views.SignUp.as_view(template_name="users/signup.html"),
        name="signup",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(success_url=reverse_lazy('index'),template_name="users/passchange.html"),
    ),
    path("tbregister/", views.teachbaseregister, name="tbregister"),
    path("user_profile/", views.showprofilepageview, name="user_profile"),
]

templates/includes/footer.html
<p>
  © {{ year }} Copyright <span style="color:red">My</span>petpro
</p>

templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static 'img/909I-TAE6hI.png' %}"
           width="50"
           height="50"
           class="d-inline-block align-top"
           alt=""/>
      <span style="color: red;">My</span>petpro
    </a>
    <ul class="nav nav-pills">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:user_profile' %}">Профиль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'courses:getcourses' %}">Доступные курсы</a>
        </li>
        <li class="nav-item">
              <a class="nav-link link-light" href="/api/updatedb">Добавить в БД</a>
            </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="/auth/password_change">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="/auth/logout">Logout</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
          <li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link link-light" href="/auth/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light" href="/auth/signup">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

templates/includes/message.html
{% extends "base.html" %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h3>Сообщение:</h3>
        </div>
        <div class="card-body">
            <br>
            {{ message }}
            <br>
            <div class="col-md-12 p-2"></div>
        {% endblock content %}

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}