api/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view

app_name = "api"

urlpatterns = [
    path("courses/", views.GetCourses.as_view()),
    path(
        "courses/<int:courseid>/",
        views.CourseDetail.as_view(
            {
                "get": "retrieve",
            }
        ),
        name="coursedetail",
    ),
    path(
        "openapi",
        get_schema_view(
            title="Your Project",
            description="API for all things …",
            version="1.0.0",
        ),
        name="openapi-schema",
    ),
    path(
        "redoc/",
        TemplateView.as_view(
            template_name="redoc.html",
            extra_context={"schema_url": "openapi-schema"},
        ),
        name="redoc",
    ),
    path(
        "updatedb/",
        views.storecoursesindb,
        name="updatebd",
    ),
]

courses/urls.py
from django.urls import path
from . import views


app_name = "courses"
urlpatterns = [
    path(
        "get_courses/",
        views.getcoursesinfo,
        name="getcourses",
    ),
    path(
        "course_detail/<int:id>",
        views.coursedetail,
        name="coursedetail",
    ),
    path(
        "course_detail/<int:courseid>/sessionregister/<int:sessionid>",
        views.sessionregister,
        name="sessionregister",
    ),
]

drf_test_task/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path(
        "auth/", include(("django.contrib.auth.urls", "authorisation"), namespace="auth")
    ),
    path("courses/", include("courses.urls", namespace="courses")),
    path("api/", include("api.urls", namespace="api")),
]

courses/models.py
from django.db import models


class CourseProfile(models.Model):
    name = models.CharField(max_length=255, verbose_name="Course name")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Course created at"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Course updated at"
    )
    owner_id = models.IntegerField(null=True, verbose_name="Course creator id")
    owner_name = models.CharField(
        max_length=50, null=True, verbose_name="Course creator name"
    )
    thumb_url = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name="Course thumb cover url",
    )
    cover_url = models.CharField(
        max_length=255, null=True, blank=True, verbose_name="Course cover url"
    )
    description = models.CharField(null=True, blank=True,
        max_length=1000, verbose_name="Course description"
    )
    last_activity = models.DateTimeField(
        auto_now=True,
        blank=True,
        null=True,
        verbose_name="Last author's activity",
    )
    total_score = models.IntegerField(
        verbose_name="Max score listener can get"
    )
    total_tasks = models.IntegerField(verbose_name="Number of tasks in course")
    unchangeable = models.BooleanField(verbose_name="Course changeable?")
    include_weekly_report = models.BooleanField(
        verbose_name="Course statistics will be included in the weekly report"
    )
    content_type = models.IntegerField(verbose_name="Course content type")

    def __str__(self):
        return str(self.name)

courses/views.py
from django.shortcuts import render
import datetime
from django.shortcuts import render
from users import clientapi
from users.models import Profile


def getcoursesinfo(request):
    template = "courses/get_courses.html"
    courses = clientapi.getcourses(page=1, per_page=50)
    context = {
        "courses": courses,
    }
    return render(request, template, context)


def coursedetail(request, id):
    template = "courses/course_detail.html"
    course = clientapi.getcoursedetail(courseid=id)
    sessions = clientapi.getcoursesessions(courseid=id)
    sessionscount = len(sessions)
    course["created_at"] = datetime.datetime.strptime(
        course["created_at"][:19], "%Y-%m-%dT%H:%M:%S"
    ).date()
    course["updated_at"] = datetime.datetime.strptime(
        course["updated_at"][:19], "%Y-%m-%dT%H:%M:%S"
    ).date()
    print(course["created_at"])
    context = {
        "course": course,
        "sessions": sessions,
        "sessionscount": sessionscount,
    }
    return render(request, template, context)


def sessionregister(request, courseid, sessionid):
    template = "courses/session_register.html"
    user = request.user
    profile, created = Profile.objects.get_or_create(user=user)
    response = clientapi.sessionregister(
        sessionid=sessionid, email=user.email, user_id=profile.externalid
    )
    context = {"user": user, "statuscode": response[0], "message": response[1]}
    return render(request, template, context)

templates/courses/course_detail.html
{% extends "base.html" %}
{% block content %}
<div class="card">
<div class="card-header">
  <h3>Подробности курса: {{ course.name }}</h3>
</div>
<div class="card-body">
<img class="fit-picture" src={{ course.thumb_url }} alt="Course cover image">
<div class="col-md-12 p-2">
  <p>Дата создания: {{ course.created_at}}</p>
  <p>Дата обновления: {{ course.updated_at }}</p>
  <p>Владелец: {{ course.owner_name }}</p>
  <p>Продолжительность: {{ course.duration }}</p>
  <p>
  <h6>Описание:</h6>
  {{ course.description|safe|truncatechars:500 }}</p>
  <p>
  <h5>Сессий доступно - {{ sessionscount }}: </h5>
  </p>
  {% for session in sessions %}
  <p> - {{ session.name }} (id {{ session.id }}) <a href="{% url 'courses:sessionregister' course.id session.id %}">записаться на эту сессию</a></p>
  {% endfor %}
  {% if user.id == profile.user.id %}
  <input type="submit" value="Записаться">
  {% endif %} 
</div>
{% endblock content %}

templates/courses/get_courses.html
{% extends "base.html" %}
{% block content %}
<div class="card">
<div class="card-header">
  <h3>Список курсов:</h3>
</div>
<div class="card-body">
<div class="col-md-12 p-2">
  <form method="">
    {% csrf_token %}
    {% for course in courses %}
    <a href="{% url 'courses:coursedetail' course.id %}">{{course.name }} </a>
    <br>
    {% endfor %}
    {% if user.id == profile.user.id %}
    <input type="submit" value="Сохранить">
    {% endif %}
  </form>
</div>
{% endblock content %}

templates/courses/session_register.html
{% extends "base.html" %}
{% block content %}
<div class="card">
<div class="card-header">
  <h3>Детали регистрации на сессию:</h3>
</div>
<div class="card-body">
<div class="col-md-12 p-2">
  Уважаемый пользователь {{user}}<br>
  {% if statuscode == 500 %}
  Возникла внутренняя ошибка приложения<br>
  Скорее всего вы не зарегистрировали пользователя на Teachbase<br>
  Вы можете это сделать на странице Профиль<br>
  {% elif statuscode == 200 %}
  Вы успешно зарегистрированы на сессию<br>
  {% elif statuscode == 403 %}
  Похоже вы уже зарегистрированы на эту сессию<br>
  {% else %}
  Возникла ошибка<br>
  Код ошибки {{statuscode}}
  {% endif %}
  {% if user.id == profile.user.id %}
  <input type="submit" value="Записаться">
  {% endif %} 
</div>
{% endblock content %}