api/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view

app_name = "api"

urlpatterns = [
    path("courses/", views.GetCourses.as_view()),
    path(
        "courses/<int:courseid>/",
        views.CourseDetail.as_view(
            {
                "get": "retrieve",
            }
        ),
        name="coursedetail",
    ),
    path(
        "openapi",
        get_schema_view(
            title="Your Project",
            description="API for all things …",
            version="1.0.0",
        ),
        name="openapi-schema",
    ),
    path(
        "redoc/",
        TemplateView.as_view(
            template_name="redoc.html",
            extra_context={"schema_url": "openapi-schema"},
        ),
        name="redoc",
    ),
    path(
        "updatedb/",
        views.storecoursesindb,
        name="updatebd",
    ),
]

drf_test_task/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path(
        "auth/", include(("django.contrib.auth.urls", "authorisation"), namespace="auth")
    ),
    path("courses/", include("courses.urls", namespace="courses")),
    path("api/", include("api.urls", namespace="api")),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordChangeView,
    PasswordResetView,
)
from . import views
from django.urls import reverse_lazy


app_name = "users"
urlpatterns = [
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "signup/",
        views.SignUp.as_view(template_name="users/signup.html"),
        name="signup",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(success_url=reverse_lazy('index'),template_name="users/passchange.html"),
    ),
    path("tbregister/", views.teachbaseregister, name="tbregister"),
    path("user_profile/", views.showprofilepageview, name="user_profile"),
]

users/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    externalid = models.CharField(max_length=25, null=True, blank=True)
    accesstoken = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.user)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile


User = get_user_model()


class CreatonForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("externalid", "accesstoken")

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields["externalid"].widget.attrs["disabled"] = "disabled"
        self.fields["accesstoken"].widget.attrs["disabled"] = "disabled"
        for name, field in self.fields.items():
            field.widget.attrs["style"] = "width:500px; height:30px;"


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs["style"] = "width:500px; height:30px;"

users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .models import Profile
from .forms import CreatonForm, UserForm, ProfileForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from . import clientapi



class SignUp(CreateView):
    form_class = CreatonForm
    success_url = reverse_lazy("index")
    template_name = "users/signup.html"


def showprofilepageview(request):
    user = request.user
    profile, created = Profile.objects.get_or_create(user=user)
    if request.method == "POST":
        form1 = ProfileForm(request.POST, instance=profile)
        form2 = UserForm(request.POST, instance=user)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            form2.save()
            return HttpResponseRedirect("/auth/user_profile/")
        else:
            print("invalid form")
            return render(
                request,
                "users/user_profile.html",
                {"form1": form1, "form2": form2},
            )
    else:
        template = "users/user_profile.html"
        accesstoken = clientapi.gettoken("/oauth/token")
        form1 = ProfileForm(
            instance=profile, initial={"accesstoken": accesstoken}
        )
        form2 = UserForm(instance=user)
        context = {
            "page_user": user,
            "profile": profile,
            "form1": form1,
            "form2": form2,
        }
        return render(request, template, context)


def teachbaseregister(request):
    template = "includes/message.html"
    user = request.user
    profile, created = Profile.objects.get_or_create(user=user)
    response = clientapi.userregister(
        email=user.email, name=user.first_name, lastname=user.last_name
    )
    if response[0] == 200:
        profile.externalid = response[1].get("id")
        profile.save()
        message = "Вы успешно зарегистрированы на Teachbase, можете записаться на сессию!"
    context = {
        "message": message,
    }
    return render(request, template, context)

templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Выход</div>
        <div class="card-body">
          <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock %}

templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
          {% endif %}
          <form method="post"
                {% if action_url %} action="{% url action_url %}" {% endif %}>
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3"
                   {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">Войти</button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock %}

templates/users/passchange.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
          {% endif %}
          <form method="post"
                {% if action_url %} action="{% url action_url %}" {% endif %}>
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3"
                   {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">Сменить пароль</button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
          {% endif %}
          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock %}

templates/users/user_profile.html
{% extends "base.html" %}
{% block content %}
  <div class="card">
    <div class="card-header">
      <h3>Профиль пользователя - {{ user }}</h3>
    </div>
    <div class="card-header">
      <a class="btn btn-secondary" href="{% url 'auth:password_change' %}">Сменить пароль</a>
      <a class="btn btn-secondary" href="{% url 'users:tbregister' %}">Зарегистрировать пользователя на Teachbase</a>
    </div>
    <div class="card-body">
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
      {% endif %}
      <div class="col-md-12 p-2">
        <form method="POST">
          {% csrf_token %}
          <table>
            {{ form2.as_table }}
            {{ form1.as_table }}
          </table>
          {% if user.id == profile.user.id %}<input type="submit" class="btn btn-primary" value="Сохранить">{% endif %}
        </form>
      </div>
    {% endblock content %}